stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - src/data/data_ingestion.py
    - data/raw
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - src/data/data_preprocessing.py
    - data/processed
    params:
    - feature_engineering.ngram_range
    - feature_engineering.max_features
    outs:
    - data/interim
    - tfidf_vectorizer.pkl
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - src/data/data_preprocessing.py
    - src/features/feature_engineering.py
    - data/processed
    - data/interim
    params:
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    - model_building.class_weight
    - model_building.objective
    - model_building.metric
    outs:
    - model/model.pkl
  model_evaluation :
    cmd : python src/model/model_evaluation.py
    deps:
    - src/data/data_preprocessing.py
    - src/features/feature_engineering.py
    - src/model/model_building.py
    - data/processed
    - data/interim
    - model/model.pkl

    params:
    - data_ingestion.test_size
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    - model_building.class_weight
    - model_building.objective
    - model_building.metric
    - feature_engineering.ngram_range
    - feature_engineering.max_features
    - model_evaluation.features

