data_ingestion:
  test_size : 0.2
feature_engineering:
  ngram_range : [1,3]
  max_features : 5000
model_building:
  learning_rate : 0.09611
  max_depth : 15
  n_estimators : 417
  class_weight : balanced
  objective :  multiclass
  metric: multi_logloss
  

  